---

- name: Template Configuration
  template:
    src: consul.conf
    dest: "{{ unbound_conf_dir }}/conf.d/consul.conf"
    mode: 0640
  notify: restart unbound

- name: Template Consul Service Definition
  template:
    src: service.json
    dest: "{{ consul_conf_dir }}/private-dns.json"
    mode: 0400
    owner: consul
  notify:
    - reload consul
