---

- import_tasks: install.yml
  when: inventory_hostname in groups['private-dns']

- import_tasks: configuration.yml
  when: inventory_hostname in groups['private-dns']

- import_tasks: dnssec.yml
  when: inventory_hostname in groups['private-dns']

- import_tasks: systemd.yml
  when: inventory_hostname in groups['private-dns']

- import_tasks: network.yml
