---

- name: Remove eth0 resolv.conf Auto Generation
  lineinfile:
    dest: /etc/sysconfig/network-scripts/ifcfg-eth0
    regexp: "PEERDNS.*$"
    line: "PEERDNS=no"
    state: present

- name: Template Network Configuration
  template:
    src: network
    dest: /etc/sysconfig/network

- name: Restart Network
  service:
    name: network
    state: restarted
