---

- name: Create Consul Template Configuration Directory
  file:
    path: "{{ consul_template_conf_dir }}"
    state: directory
    mode: 0750

- name: Template Default Configuration
  template:
    src: default.hcl
    dest: "{{ consul_template_conf_dir }}/"
    mode: 0640
  notify: restart consul template
