---

- name: Add PGDG
  yum:
    name: https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat/rhel-7-x86_64/pgdg-redhat96-{{ postgres_version }}-3.noarch.rpm
    state: present

- name: Install Server
  yum:
    name: postgresql96-server
    disablerepo: base,updates
    state: present

- name: Register PG VERSION File Exists
  stat:
    path: "{{ postgres_data_dir }}/PG_VERSION"
  register: postgres_pg_version_exists_task
- set_fact:
    postgres_pg_version_exists: "{{ postgres_pg_version_exists_task.stat.exists }}"
- debug:
    var: postgres_pg_version_exists

- name: Initialize Server
  command: /usr/pgsql-{{ postgres_version }}/bin/postgresql96-setup initdb
  when: not postgres_pg_version_exists
